modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
credits="Idea and textures by edmord, coding by ilja615" #optional
license="LGPL" #mandatory
[[mods]] #mandatory
modId="fish_in_planks" #mandatory
version="1.16.5-0.2" #mandatory
displayName="Fish in Planks" #mandatory
description='''
Craft 9 of the same fishes to get a fish barrel, a brand new decorative block that can be placed in any of the 6 orientations you like!
'''